
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:ft_inception
    env_file:
      - .env
    volumes:
      - DB:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$(cat /run/secrets/db_root_password)"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db_root_password
      - db_password

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:ft_inception
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - WordPress:/var/www/html
    expose:
      - "9000"
    networks:
      - inception_net
    restart: unless-stopped
    secrets:
      - db_password
      - wp_admin_password
      - wp_editor_password

  nginx:
      container_name: nginx
      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
      image: nginx:ft_inception
      ports:
        - "443:443"
      depends_on:
        wordpress:
          condition: service_started
      volumes:
        - WordPress:/var/www/html
      networks:
        - inception_net
      restart: unless-stopped
      secrets:
        - inception_crt
        - inception_key

volumes:
  DB:
    name: DB
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/DB
      o: bind
  WordPress:
    name: WordPress
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/WordPress
      o: bind

networks:
  inception_net:
    name: inception_net
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_editor_password:
    file: ../secrets/wp_editor_password.txt
  inception_crt:
    file: ../secrets/inception.crt
  inception_key:
    file: ../secrets/inception.key